SELECT 'PROJECT '|| chr(64 + CLIENT_ID ) NAME,  DATEDIFF(mm, START_DATE , FINISH_DATE ) MONTH_COUNT FROM PROJECT  JOIN CLIENT  ON  PROJECT. CLIENT_ID = CLIENT.ID WHERE DATEDIFF(mm, START_DATE , FINISH_DATE )=(
SELECT  MAX(DATEDIFF(mm, START_DATE , FINISH_DATE )) MONTH_COUNT FROM PROJECT );
