SELECT CLIENT .NAME , COUNT(CLIENT_ID) PROJECT_COUNT 
FROM PROJECT  
JOIN CLIENT 
ON PROJECT .CLIENT_ID =CLIENT .ID 
GROUP BY CLIENT_ID 
HAVING PROJECT_COUNT=(SELECT   MAX(PROJECT_COUNT) FROM (SELECT COUNT(CLIENT_ID) PROJECT_COUNT FROM PROJECT  GROUP BY CLIENT_ID ));