CREATE TABLE WORKER (
ID IDENTITY PRIMARY KEY,
NAME VARCHAR (1000) CHECK (Length(name)>2) NOT NULL,
BIRTHDAY DATE CHECK (BIRTHDAY>'1900-12-31'),
LEVEL VARCHAR (10) CHECK (LEVEL IN('Trainee', 'Junior', 'Middle', 'Senior')) NOT NULL,
SALARY INT CHECK (SALARY>100 AND SALARY<100000) 
);

CREATE TABLE CLIENT (
ID IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR (1000) CHECK (Length(name)>2) NOT NULL
);

CREATE TABLE  PROJECT (
ID IDENTITY(1,1) PRIMARY KEY,
CLIENT_ID BIGINT NOT NULL,
START_DATE  DATE,
FINISH_DATE DATE,
FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);

CREATE TABLE  PROJECT_WORKER (
PROJECT_ID BIGINT NOT NULL,
WORKER_ID BIGINT NOT NULL,
FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID),
FOREIGN KEY (WORKER_ID) REFERENCES WORKER(ID),
PRIMARY KEY (PROJECT_ID, WORKER_ID)
);