SELECT 
'PROJECT '|| chr(64 + PROJECT_ID  ) NAME,
DATEDIFF(mm, PROJECT .START_DATE , PROJECT .FINISH_DATE )*
SUM(WORKER .SALARY)  PRICE
FROM PROJECT_WORKER 
INNER JOIN WORKER   ON  PROJECT_WORKER .WORKER_ID  = WORKER .ID 
INNER JOIN PROJECT   ON  PROJECT_WORKER .PROJECT_ID   = PROJECT .ID 
GROUP BY PROJECT_ID;
